apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: k8s-serv-deployment
spec:
  selector:
    matchLabels:
      app: k8s-serv
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: k8s-serv
    spec:
      containers:
      - name: k8s-serv
        image: sklevenz/k8s-serv:0.5.0
        ports:
        - containerPort: 8080
