apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: k8s-serv-deployment
  namespace: k8s-serv-snapshot
spec:
  selector:
    matchLabels:
      app: k8s-serv
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: k8s-serv
    spec:
      containers:
      - name: k8s-serv
        image: sklevenz/k8s-serv:snapshot
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-serv-service
spec:
  type: LoadBalancer
  selector:
    app: k8s-serv
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
